# Generated by Django 5.0.14 on 2026-07-07 01:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'branches',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('min_stock_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('category', models.CharField(choices=[('INSUMO', 'Insumo'), ('MATERIA PRIMA', 'Materia Prima'), ('LICOR', 'Licores y Destilados')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingredients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('production_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='media-savannah/')),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnitMeasures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('abbreviation', models.TextField()),
            ],
            options={
                'db_table': 'unit_measures',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InventoryMovements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost_at_time', models.DecimalField(decimal_places=4, max_digits=10)),
                ('movement_type', models.CharField(choices=[('INGRESO', 'Ingreso de Mercancía'), ('AJUSTE', 'Ajuste de Inventario'), ('MERMA', 'Merma / Desperdicio')], default='INGRESO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.branches')),
                ('ingredient', models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredients')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'db_table': 'inventory_movements',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_required', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.ingredients')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipes_set', to='inventory.products')),
            ],
            options={
                'db_table': 'recipes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('total_sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('table_name', models.CharField(default='Barra', max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_prepared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_cost_at_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.branches')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
            ],
            options={
                'db_table': 'sales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transformations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_produced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_ingredient', models.ForeignKey(db_column='result_ingredient_id', on_delete=django.db.models.deletion.PROTECT, related_name='produced_in', to='inventory.ingredients')),
            ],
            options={
                'verbose_name': 'Transformación',
                'db_table': 'transformations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransformationItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.PROTECT, to='inventory.ingredients')),
                ('transformation', models.ForeignKey(db_column='transformation_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.transformations')),
            ],
            options={
                'verbose_name': 'Ítem de Transformación',
                'db_table': 'transformation_items',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ingredients',
            name='unit_measure',
            field=models.ForeignKey(blank=True, db_column='unit_measure_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.unitmeasures'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.TextField(choices=[('OWNER', 'Dueño de Negocio (Acceso Total)'), ('ADMIN_SEDE', 'Administrador de Sede'), ('STAFF', 'Personal (Caja/Barra)')], default='STAFF')),
                ('branch', models.ForeignKey(blank=True, db_column='branch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.branches')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_level', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('last_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.branches')),
                ('ingredient', models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.ingredients')),
            ],
            options={
                'db_table': 'inventories',
                'managed': True,
                'unique_together': {('branch', 'ingredient')},
            },
        ),
    ]
