# Generated by Django 5.0.14 on 2026-07-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='preparation_area',
            field=models.CharField(choices=[('BAR', 'Barra de Cócteles'), ('COCINA', 'Cocina / Alimentos')], default='BAR', max_length=15),
        ),
    ]
