# Generated by Django 5.0.14 on 2026-07-15 18:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_products_preparation_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'payment_methods',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_method',
            field=models.ForeignKey(db_column='payment_method_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='inventory.paymentmethods'),
            preserve_default=False,
        ),
    ]
