# Generated by Django 5.0.14 on 2026-08-25 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_paymentmethods_sales_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.ForeignKey(blank=True, db_column='payment_method_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.paymentmethods'),
        ),
    ]
